#+STARTUP: content
#+OPTIONS: \n:t
#+TITLE:	Hugo and Org-mode
#+EXPORT_FILE_NAME: hugo-and-org-mode
#+AUTHOR:	Shawn Dennis Lin
#+EMAIL:	ShawnDennisLin@gmail.com
#+DATE:	[2020-11-15 Wed]

#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

#+SEQ_TODO: TODO DRAFT DONE
#+PROPERTY: header-args :eval no

#+HUGO_BASE_DIR: ~/shdennlin.github.io
#+HUGO_SECTION: /posts/blog/hugo/

#+hugo_menu: :menu sidebar :name Hugo and Org-mode :identifier blog-hugo-and-org-mode :parent blog :weight auto
#+HUGO_CATEGORIES: Blog
#+HUGO_TAGS: Hugo org-mode
#+HUGO_DRAFT: false
#+hugo_custom_front_matter: :hero /posts/blog/hugo/images/hugo.png

This is my note for Hugo + Emacs.

#+HUGO: more

** Install
To see [[https://gohugo.io/getting-started/installing/][Official Website]]

** Tutorials
- [[https://toha-guides.netlify.app/posts/getting-started/prepare-site/][Getting Started]](theme with Toha)
   
** Common command
*** Create Site
#+begin_src shell
hugo new site ./ -f=yaml --force
#+end_src
*** Add theme
#+begin_src shell
git submodule add https://github.com/hugo-toha/toha.git themes/toha
#+end_src
*** Run Site Locally
#+begin_src shell
hugo server -t toha -w
#+end_src
If you navigate to http://localhost:1313, you should see a basic site with Toha theme. In the next section, we are going to configure the site to look like the hugo-toha.github.io. As we have run the server in watch mode, any changes we make to the site will be instantly visible in the browser.

** Hugo Related Documentation
- [[https://www.saotn.org/hugo-development-environment-in-wsl-2/][Hugo development environment in WSL 2]]

** Theme
You can find the theme from [[https://themes.gohugo.io/][themes.gohugo.io]], these is my recommended theme:
1. [[https://themes.gohugo.io/toha/][Toha]](Download) [[https://github.com/hugo-toha/toha][hugo-toha/toha]](GitHub) [[https://github.com/hugo-toha/guides][hugo-toha/guides]](GitHub)
   
** org-mode + Hugo
- [[https://ox-hugo.scripter.co/][ox-hugo]] 
- [[https://www.xianmin.org/post/ox-hugo/][博客写作流程之工具篇： emacs, orgmode, hugo & ox-hugo]]
- [[https://www.shanesveller.com/blog/2018/02/13/blogging-with-org-mode-and-ox-hugo/][Blogging with org-mode and ox-hugo]]
   
*** useful plugins in emacs
1. [[https://github.com/kaushalmodi/ox-hugo/tree/f24c9bd522ae22bee2327c2b53858d0a5066707d][ox-hugo]](Github)

   ~ox-hugo~ is an Org exporter backend that exports Org to Hugo-compatible Markdown (Blackfriday) and also generates the front-matter (in TOML or YAML format).
   
   If you use spacemacs, you can use ~, e e H~ or ~SPC m e e H~ to export org file to markdown.
   For More information about spacemacs , please see [[https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemacs/org][spacemacs/org]].
   
3. [[https://github.com/masasam/emacs-easy-hugo/tree/dffe165de354c2e6dc16510edad09839e69fdd35][eaxy-hugo]](Github)
4. [[https://github.com/rejeep/prodigy.el/tree/6ae71f27b09b172f03fb55b9eeef001206baacd3][prodigy]](Github)
   
   Manage external services from within Emacs.
   If you use spacemacs, you can use ~<SPC> a t p~ to see a list of all defined services.
   For More information about spacemacs , please see [[https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Btools/prodigy][spacemacs/prodigy]].
   
***  


