#+STARTUP: content
#+TITLE:	Linux Install Application
#+AUTHOR:	Shawn Dennis Lin
#+EMAIL:	ShawnDennisLin@gmail.com
#+DATE:	[2020-11-19 Thu]

#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

#+SEQ_TODO: TODO DRAFT DONE
#+PROPERTY: header-args :eval no

#+HUGO_BASE_DIR: ../../../../
#+HUGO_SECTION: /posts/Linux/linux_install_application

#+hugo_menu: :menu sidebar :name Linux Install Application :identifier linux-install-app :parent linux :weight auto
#+HUGO_CATEGORIES: linux
#+HUGO_TAGS: linux
#+HUGO_DRAFT: false
#+hugo_custom_front_matter: :hero /posts/Linux/linux_install_application/images/linux.png

These are the applications I installed in linux. If you have any questions about these apps, you can contact me.

#+HUGO: more

** My Install Application in Linux
*** update & upgrade  
#+BEGIN_SRC shell
sudo apt-get update && sudo apt-get -y upgrade
#+END_SRC
or
#+BEGIN_SRC shell
sudo apt-get update && sudo apt-get -y dist-upgrade
#+END_SRC

+ Ref: [[https://blog.longwin.com.tw/2008/03/debian_ubuntu_apt_dist_upgrade_difference_2008/][APT upgrade 和 dist-upgrade 的差別]] 
    
*** Git
#+BEGIN_SRC shell
sudo apt-get -y install git
#+END_SRC
    
*** dotfiles
#+BEGIN_SRC shell
mkdir ~/.dotfiles &&\
git clone https://github.com/shdennlin/dotfiles.git ~/.dotfiles/. &&\
cd ~/.dotfiles &&\
bash install.sh &&\
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
#+END_SRC
+ GitHub: [[https://github.com/shdennlin/dotfiles][shdennlin/dotfiles]]  
    
*** fcitx & boshiamy
#+BEGIN_SRC shell
sudo apt-get install -y fcitx fcitx-table-boshiamy fcitx-chewing
#+END_SRC
+ Ref: [[https://thorasgard520.blogspot.com/2019/04/linux-ubuntu-fcitx.html][Linux Ubuntu 嘸蝦米輸入法的FCITX安裝]] 
    
*** GNOME
#+BEGIN_SRC shell
sudo apt install -y gnome-tweaks gnome-shell-extensions &&\
sudo apt install -y chrome-gnome-shell &&\
sudo apt purge gnome-shell-extenion-appindicator 

sudo apt install gnome-shell-extension-pixelsaver &&\
sudo apt install gnome-shell-extension-remove-dropdown-arrows &&\
sudo apt install gnome-shell-extension-system-monitor &&\
sudo apt install gnome-shell-extension-prefs &&\
sudo apt-get install gnome-shell-pomodoro
#+END_SRC
+ Ref: [[https://www.itread01.com/content/1544311459.html][針對Gnome 3的Linux桌面進行美化]] 

*** Anaconda
#+BEGIN_SRC shell
cd ~/Downloads
wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
bash ~/Dwonloads/Anaconda3-2020.02-Linux-x86_64.sh
conda create -n tf-gpu tensorflow-gpu
conda activate tf-gpu
#+END_SRC

*** Angry IP scanner
+ GitHub: [[https://github.com/angryip/ipscan/tree/3.7.2][angryip/ipscan]]  
+ Ref: [[https://angryip.org/about/][Angry IP Scanner]] 

*** BingWall - Bing wallpaper of the day
#+BEGIN_SRC shell
sudo snap install bing-wall
#+END_SRC
+ Ref: [[https://snapcraft.io/bing-wall][BingWall - Bing wallpaper of the day]] 

*** boot-repair
#+BEGIN_SRC shell
sudo add-apt-repository ppa:yannubuntu/boot-repair &&\
sudo apt-get update &&\
sudo apt-get install -y boot-repair && boot-repair
#+END_SRC
+ Ref: [[https://help.ubuntu.com/community/Boot-Repair][Boot-Repair]] 

*** bpytop
Resource monitor that shows usage and stats for processor, memory, disks, network and processes. Python port of bashtop.
#+BEGIN_SRC shell
cd ~/Downloads &&\
git clone https://github.com/aristocratos/bpytop.git &&\
cd bpytop &&\
sudo make install
#+END_SRC
+ GitHub: [[https://github.com/aristocratos/bpytop][aristocratos/bpytop]]  

*** Crow Translate
A small translate tool like QTranslate.
#+BEGIN_SRC shell
cd ~/Downloads &&\
git clone https://aur.archlinux.org/crow-translate.git
cd crow-translate
makepkg -si
#+END_SRC
+ GitHub: [[https://github.com/crow-translate/crow-translate][crow-translate/crow-translate]]
+ Ref: [[https://crow-translate.github.io/][Crow Translate]]

*** Discord
#+BEGIN_SRC shell
cd ~/Downloads &&\
wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb" &&\
sudo dpkg -i discord.deb
#+END_SRC
+ Ref: [[https://discord.com/][Discord]] 

*** extra-cmake-modules
#+BEGIN_SRC shell
cd ~/Downloads &&\
git clone https://github.com/KDE/extra-cmake-modules.git &&\
cd extra-cmake-modules &&\
mkdir build &&\
cd build &&\
cmake ..  &&\
make &&\
sudo make install
#+END_SRC
+ GitHub: [[https://github.com/KDE/extra-cmake-modules][KDE/extra-cmake-modules]] 

*** flatpak
#+BEGIN_SRC shell
sudo apt install -y flatpak
#+END_SRC
+ Ref: [[https://zh.wikipedia.org/wiki/Flatpak][flatpak]](wiki)

*** font
#+BEGIN_SRC shell
cd ~/Downloads &&\
git clone https://github.com/shdennlin/linux-configuration.git &&\
cd ~/Downloads/linux-configuration/fonts &&\
bash install.sh
#+END_SRC
+ GitHub: [[https://github.com/shdennlin/linux-configuration][shdennlin/linux-configuration]] 

*** FreeCAD
#+BEGIN_SRC shell
sudo apt install -y freecad
#+END_SRC

*** FSearch
#+BEGIN_SRC shell
sudo add-apt-repository ppa:christian-boxdoerfer/fsearch-daily &&\
sudo apt-get update &&\
sudo apt install fsearch-trunk
#+END_SRC
+ GitHub: [[https://github.com/cboxdoerfer/fsearch][cboxdoerfer/fsearch]] 

*** gdrive
#+BEGIN_SRC shell
cd ~/Downloads &&\
wget -O drive https://drive.google.com/uc?id=0B3X9GlR6Embnb095MGxEYmJhY2c &&\
sudo install drive /usr/local/bin/drive
#+END_SRC
+ GitHub: [[https://github.com/prasmussen/gdrive][prasmussen/gdrive]]  
+ Ref: [[https://hiraku.tw/2020/01/5894/][如何在終端機介面使用 Google Drive (gdrive cmd)]] 

*** GitKraken
#+BEGIN_SRC shell
wget https://release.gitkraken.com/linux/gitkraken-amd64.deb ~/Downloads &&\
sudo dpkg -i ~/Downloads/gitkraken-amd64.deb
#+END_SRC
+ Ref: [[https://www.gitkraken.com/][GitKrakon]] 

*** Java
Preparation: Download jre-8u251-linux-x64.tar.gz
Download location: [[https://java.com/en/download/linux_manual.jsp][Java Downloads for Linux]] 
#+BEGIN_SRC shell
cd /usr &&\
sudo mkdir java &&\
cd java &&\
sudo mv ~/Downloads/jre-8u251-linux-x64.tar.gz . &&\
sudo tar zxvf jre-8u251-linux-x64.tar.gz &&\
sudo rm -rf jre-8u251-linux-x64.tar.gz
#+END_SRC
+ Preparation: Download jre-8u251-linux-x64.tar.gz
+ Ref: [[https://java.com/en/download/linux_manual.jsp][Java Downloads for Linux]]  

*** KiCad
#+BEGIN_SRC shell
sudo add-apt-repository --yes ppa:js-reynaud/kicad-4 ; &&\
sudo apt-get update ; &&\
sudo apt-get install -y kicad
#+END_SRC
+ Ref: [[https://kicad.org/download/ubuntu/][KiCad Install on Ubuntu]]

*** Latex
#+BEGIN_SRC shell
sudo apt-get install texlive-base &&\
sudo apt-get install texlive-latex-recommended &&\
sudo apt-get install texlive &&\
sudo apt-get install texlive-latex-extra &&\
sudo apt-get install texlive-xetex
#+END_SRC
+ Ref: [[https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux][How to install LaTex on Ubuntu 20.04 Focal Fossa Linux]] 

*** linux-wifi-hotspot
#+BEGIN_SRC shell
git clone https://github.com/lakinduakash/linux-wifi-hotspot
cd linux-wifi-hotspot

#build binaries
make

#install
sudo make install
#+END_SRC
+ GitHub: [[https://github.com/lakinduakash/linux-wifi-hotspot][lakinduakash/linux-wifi-hotspot]] 

*** Logitech MX Master
First:
#+BEGIN_SRC shell
sudo apt install -y cmake libevdev-dev libudev-dev libconfig++-dev &&\
mkdir -p ~/Downloads/logiops &&\
git clone https://github.com/PixlOne/logiops.git ~/Downloads/logiops/  &&\
cd ~/Downloads/logiops &&\
mkdir build &&\
cd build &&\
cmake .. &&\
make &&\
sudo make install &&\
sudo systemctl start logid
#+END_SRC
Second:
#+BEGIN_SRC shell
mkdir -p ~/Downloads/logitech-mouse-config &&\
git clone https://github.com/shdennlin/logitech-mouse-config.git ~/Downloads/logitech-mouse-config/ &&\
cd ~/Downloads/logitech-mouse-config/ &&\
bash install.sh
#+END_SRC
+ GitHub: [[https://github.com/shdennlin/logitech-mouse-config][shdennlin/logitech-mouse-config]]  
+ Ref: See GitHub

*** MusixMatch
#+BEGIN_SRC shell
sudo snap install musixmatch
#+END_SRC
+ GitHub:   
+ Ref: [[https://snapcraft.io/musixmatch][Install Musixmatch on your Linux distribution]] 

*** nomacs
nomacs is a free, open source image viewer, which supports multiple platforms. You can use it for viewing all common image formats including RAW and psd images.
#+BEGIN_SRC shell
sudo apt install nomacs &&\
sudo apt-get install nomacs-l10n
#+END_SRC
+ Ref: [[https://nomacs.org/\\][nomacs.org]] 

*** nvtop
Nvtop stands for NVidia TOP, a (h)top like task monitor for NVIDIA GPUs. It can handle multiple GPUs and print information about them in a htop familiar way.
#+BEGIN_SRC shell
sudo apt install -y nvtop
#+END_SRC
+ GitHub: [[https://github.com/Syllo/nvtop][Syllo/nvtop]]

*** Okular
Okular is a universal document viewer developed by KDE. Okular works on multiple platforms, including but not limited to Linux, Windows, macOS, *BSD, etc.
#+BEGIN_SRC shell
sudo apt-get install okular
#+END_SRC
+ Ref: [[https://okular.kde.org/][okular.kde.org]] 

*** Open Broadcaster Software Studio (OBS)
Free and open source software for video recording and live streaming.
#+BEGIN_SRC shell
sudo add-apt-repository ppa:obsproject/obs-studio ;\
sudo apt update ;\
sudo apt install -y obs-studio
#+END_SRC
+ Ref1: [[https://obsproject.com/][obsproject.com]] 
+ Ref2: [[https://itsfoss.com/best-linux-screen-recorders/][9 Best Screen Recorders For Linux]]

*** rar, zip
#+BEGIN_SRC shell
apt-get install -y unrar &&\
sudo apt install -y p7zip-full
#+END_SRC

*** screenfetch
screenFetch is a "Bash Screenshot Information Tool". This handy Bash script can be used to generate one of those nifty terminal theme information + ASCII distribution logos you see in everyone's screenshots nowadays. It will auto-detect your distribution and display an ASCII version of that distribution's logo and some valuable information to the right. There are options to specify no ASCII art, colors, taking a screenshot upon displaying info, and even customizing the screenshot command! This script is very easy to add to and can easily be extended.
#+BEGIN_SRC shell
apt install screenfetch
#+END_SRC
+ GitHub:  [[https://github.com/KittyKatt/screenFetch][KittyKatt/screenFetch]] 

*** spacemacs
Spacemacs is a new way to experience Emacs -- a sophisticated and polished set-up focused on ergonomics, mnemonics and consistency.

Just clone it, launch it, then press the space bar to explore the interactive list of carefully-chosen key bindings. You can also press the home buffer's [?] button for some great first key bindings to try.

Spacemacs can be used naturally by both Emacs and Vim users -- you can even mix the two editing styles. Switching easily between input styles makes Spacemacs a great tool for pair-programming.

Spacemacs is currently in beta, and contributions are very welcome.
#+BEGIN_SRC shell
git clone -b develop https://github.com/syl20bnr/spacemacs.git ~/.emacs.d &&\
git clone https://github.com/bitjockey42/spacemacs-jekyll.git ~/.emacs.d/private/jekyll &&\
git clone https://github.com/shdennlin/spacemacs-private.git ~/.spacemacs.d
#+END_SRC
+ GitHub1: [[https://github.com/syl20bnr/spacemacs][syl20bnr/spacemacs]] 
+ GitHub2: [[https://github.com/shdennlin/spacemacs-private][shdennlin/spacemacs-private]] 
+ Ref: [[https://www.spacemacs.org/][spacemacs.org]]  

*** Spotify
#+BEGIN_SRC shell
sudo apt install -y snapd &&\
sudo snap install spotify
#+END_SRC

*** Tensorflow-gpu
#+BEGIN_SRC shell
cd ~/Downloads
wget http://tw.download.nvidia.com/XFree86/Linux-x86_64/440.82/NVIDIA-Linux-x86_64-440.82.run
#+END_SRC
+ Ref: [[https://illya13.github.io/RL/tutorial/2020/04/26/installing-tensorflow-on-ubuntu-20.html][Installing TensorFlow 2 with GPU support on Ubuntu 20.04 LTS]] 

*** Terminator
Originally created and developed for a long time by Chris Jones, the goal of this project is to produce a useful tool for arranging terminals. It is inspired by programs such as gnome-multi-term, quadkonsole, etc. in that the main focus is arranging terminals in grids (tabs is the most common default method, which Terminator also supports).

Much of the behaviour of Terminator is based on GNOME Terminal, and we are adding more features from that as time goes by, but we also want to extend out in different directions with useful features for sysadmins and other users. If you have any suggestions, please file wishlist bugs! (see below for the address)
#+BEGIN_SRC shell
sudo apt install terminator
#+END_SRC
+ Ref: [[https://gnometerminator.blogspot.com/p/introduction.html][Introduction-Terminator]] 

*** Linux Advanced Power Management (TLP)
TLP is a feature-rich command line utility for Linux, saving laptop battery power without the need to delve deeper into technical details.

TLP’s default settings are already optimized for battery life and implement Powertop’s recommendations out of the box. So you may just install and forget it.

Nevertheless TLP is highly customizable to fulfil your specific requirements.

#+BEGIN_SRC shell
sudo add-apt-repository ppa:linrunner/tlp &&\
sudo apt update &&\
sudo apt install tlp tlp-rdw &&\
sudo apt-get install smartmontools &&\
sudo systemctl start tlp &&\
sudo tlp-stat | less
#+END_SRC
+ Ref: [[https://github.com/twtrubiks/linux-note/tree/master/linux-tlp-tutorial][linux tlp tutorial]]
+ Ref: [[https://linrunner.de/tlp/][TLP - Optimize Linux Laptop Battery Life]] 

*** Vim
#+BEGIN_SRC shell
sudo apt-get install vim
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
#+END_SRC
+ Ref: [[https://github.com/shdennlin/dotfiles][shdennlin/dotfiles]] 

*** Wine
Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, macOS, & BSD. Instead of simulating internal Windows logic like a virtual machine or emulator, Wine translates Windows API calls into POSIX calls on-the-fly, eliminating the performance and memory penalties of other methods and allowing you to cleanly integrate Windows applications into your desktop.
+ Ref: [[https://wiki.winehq.org/Download][Supported Wine]] 
+ Ref: [[https://wiki.winehq.org][winehq.org]] 

*** xclip
xclip is a command line interface to the X11 clipboard. It allows you to put the output of a command directly into the clipboard so that you don't have to copy&paste from the terminal manually (which can be a tedious task especially if the output is very long). It also allows you to put the contents of a file directly into the clipboard. 
#+BEGIN_SRC shell
sudo apt-get install -y xclip
#+END_SRC
+ GitHub:  
+ Ref: [[https://www.howtoforge.com/command-line-copy-and-paste-with-xclip-debian-ubuntu][Command-Line Copy&Paste With xclip (Debian/Ubuntu)]] 


